repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0  # You can update this to the latest stable version
    hooks:
      - id: black
        args: ["--line-length=88"]
        language_version: python3
        files: '\.py$' 
